version: "3"

services:
  app:
    image: timetracker:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - SERVER_IP=0.0.0.0
      - DATABASE_HOST=db
    depends_on:
      - db
    volumes:
      - ./logs:/usr/app/logs
      - ./credentials.json:/usr/app/credentials.json
      - ./app.env:/usr/app/app.env
      - ./auth.env:/usr/app/auth.env
    stop_signal: SIGINT
  db:
    image: postgres
    env_file:
      - .env
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    ports:
      - 5432:5432
volumes:
  dbdata:
