version: "3"

services:
  app:
    image: timetracker:latest
    env_file:
      - app.env
      - auth.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    stop_signal: SIGINT
  db:
    image: postgres
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    ports:
      - 5432:5432
volumes:
  dbdata:
